### ISSUE TITLE
 incompatible version of Sass

### ISSUE THREAD

**Issue by lgs** [radiant/radiant-prototype#3]
lsoave@ubuntu:~/rails/serve/radiant-prototype$ serve
/home/lsoave/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.11.5/lib/compass/sass_extensions.rb:2:in `<top (required)>': It looks like you've got an incompatible version of Sass. This often happens when you have an old haml gem installed. Please upgrade Haml to v3.1 or above. (LoadError)

**Comment by cleverlemming** [comment]
I had this problem with Radiant 0.9.1 and Ruby 1.8.7x. Solution was to install a new Ruby and rebuild my gem repository. Compass only worked with a specific patch level of Ruby. In my case, the only way to get rid of this error was to use ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-darwin10.8.0] and Compass 0.11.1.

**Comment by lgs** [comment]
many thanks cleverlemming
