### ISSUE TITLE
NoMethodError at /admin/pages 

### ISSUE THREAD

**Issue by mandric** [radiant/radiant-prototype#5]
Just installed and ran serve but when I hit the page at port 4000 I get an error:

NoMethodError at /admin/pages
undefined method `append_image_extension' for #Serve::DynamicHandler::Context:0x104bd6e60

I'm not very familiar with rails but it's probably something simple like a gem I'm missing.

**Comment by jlong** [comment]
This should be fixed now. Please pull.

**Comment by mandric** [comment]
Works, thanks!
